"""Add user preferences

Revision ID: ed0edbd50a47
Revises: d2f4e8b1a3c5
Create Date: 2026-09-13 18:13:58.123759
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0edbd50a47'
down_revision: Union[str, None] = 'd2f4e8b1a3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listings_tsv'), table_name='job_listings', postgresql_using='gin')
    op.create_index('ix_job_listings_tsv', 'job_listings', [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(company, '') || ' ' || coalesce(raw_text, ''))")], unique=False, postgresql_using='gin')
    op.alter_column('user_listing_matches', 'change_alert',
               existing_type=sa.TEXT(),
               comment='Alert summary if saved listing was modified or taken down',
               existing_nullable=True)
    op.add_column('users', sa.Column('onboarded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'onboarded')
    op.alter_column('user_listing_matches', 'change_alert',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Alert summary if saved listing was modified or taken down',
               existing_nullable=True)
    op.drop_index('ix_job_listings_tsv', table_name='job_listings', postgresql_using='gin')
    op.create_index(op.f('ix_job_listings_tsv'), 'job_listings', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(company, ''::character varying)::text) || ' '::text) || COALESCE(raw_text, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
